dist: bionic

language: go
go: "1.12"
env:
  - GO111MODULE=on
  # - PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
before_install:
  - sudo apt-get update
  - sudo apt-get install libelektra4
  - dpkg-query -L libelektra4